//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchProduct
    {
        public int Id { get; set; }
        public int BatchRequisitionId { get; set; }
        public int ProductId { get; set; }
        public int EstimatedQuantity { get; set; }
    
        public virtual BatchRequisition BatchRequisition { get; set; }
        public virtual Product Product { get; set; }
    }
}
