//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchRequisition()
        {
            this.BatchProduct = new HashSet<BatchProduct>();
            this.BatchRequisitionDetail = new HashSet<BatchRequisitionDetail>();
            this.BatchRequisitionProductionEstimation = new HashSet<BatchRequisitionProductionEstimation>();
            this.FloorStoreRawMaterial = new HashSet<FloorStoreRawMaterial>();
        }
    
        public int Id { get; set; }
        public int ProductionGroupId { get; set; }
        public int BatchRequisitionNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<System.DateTime> DeliveredOn { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<int> SendToProductionBy { get; set; }
        public Nullable<System.DateTime> SendToProductionOn { get; set; }
        public Nullable<System.DateTime> EstimatedProductionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProduct> BatchProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRequisitionDetail> BatchRequisitionDetail { get; set; }
        public virtual ProductionGroup ProductionGroup { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRequisitionProductionEstimation> BatchRequisitionProductionEstimation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorStoreRawMaterial> FloorStoreRawMaterial { get; set; }
    }
}
