//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHolidays
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime HolidayDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
