//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashedGood
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public int ProductQuantity { get; set; }
        public int InvoiceId { get; set; }
        public int CustomerId { get; set; }
        public int GroupId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DamageStatusId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Group Group { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ProductDamageStatusType ProductDamageStatusType { get; set; }
    }
}
