//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerHistory
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int CustomerCode { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerPhone { get; set; }
        public string OwnerName { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerPhone { get; set; }
        public Nullable<System.DateTime> OwnerBirthDate { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonMobile { get; set; }
        public string PrimaryContactNo { get; set; }
        public string Village { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public string Email { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> CustomerStatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual Area Area { get; set; }
        public virtual CustomerStatus CustomerStatus { get; set; }
        public virtual PostOffice PostOffice { get; set; }
    }
}
