//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAttachment
    {
        public int Id { get; set; }
        public System.Guid FileGuid { get; set; }
        public int CustomerId { get; set; }
        public int AttachmentTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual FileType FileType { get; set; }
    }
}
