//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTransaction()
        {
            this.CustomerTransactionDetail = new HashSet<CustomerTransactionDetail>();
        }
    
        public int Id { get; set; }
        public int CashBankAccountHeadId { get; set; }
        public string TransactionReference { get; set; }
        public double TransactionAmount { get; set; }
        public Nullable<int> CashBankTransactionDetailId { get; set; }
        public Nullable<int> BankChargeAccountHeadId { get; set; }
        public Nullable<double> BankChargeAmount { get; set; }
        public Nullable<int> BankChargeTransactionDetailId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> TransactionEntryId { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
        public virtual TransactionDetail TransactionDetail1 { get; set; }
        public virtual TransactionEntry TransactionEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransactionDetail> CustomerTransactionDetail { get; set; }
    }
}
