//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransactionDetail
    {
        public int Id { get; set; }
        public int CustomerTransactionId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> BookNo { get; set; }
        public Nullable<int> BookSerialNo { get; set; }
        public double TransactionAmount { get; set; }
        public Nullable<int> TransactionDetailId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerTransaction CustomerTransaction { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
