//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandOrderDetail
    {
        public int Id { get; set; }
        public int DemandOrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> Discount { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual DemandOrder DemandOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
