//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandOrder()
        {
            this.DemandOrderDetail = new HashSet<DemandOrderDetail>();
            this.DemandOrderDiscountTransaction = new HashSet<DemandOrderDiscountTransaction>();
            this.DemandOrderTransaction = new HashSet<DemandOrderTransaction>();
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int Id { get; set; }
        public int DemandOrderNo { get; set; }
        public int CustomerId { get; set; }
        public int DemandOrderTypeId { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public System.DateTime DODate { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ReferenceDONo { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public Nullable<int> ReturnedBy { get; set; }
        public Nullable<System.DateTime> ReturnedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DeliveryConfirmedBy { get; set; }
        public Nullable<System.DateTime> DeliveryConfirmedOn { get; set; }
        public bool IsCurrentRecord { get; set; }
        public Nullable<int> PreviousId { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> RejectedReasonTypeId { get; set; }
        public int SaleTypeId { get; set; }
        public int DemandOrderStatusId { get; set; }
        public Nullable<int> DemandOrderTransactionId { get; set; }
        public double TotalAmount { get; set; }
        public Nullable<double> RegularDiscountInPercentage { get; set; }
        public Nullable<double> RegularDiscountAmount { get; set; }
        public Nullable<double> SpecialDiscountInPercentage { get; set; }
        public Nullable<double> SpecialDiscountAmount { get; set; }
        public Nullable<double> AdditionalDiscountInPercentage { get; set; }
        public Nullable<double> AdditionalDiscountAmount { get; set; }
        public Nullable<double> ExtraDiscountInPercentage { get; set; }
        public Nullable<double> ExtraDiscountAmount { get; set; }
        public Nullable<double> CashBackAmount { get; set; }
        public Nullable<double> TotalDiscountAmount { get; set; }
        public double TotalGrandAmount { get; set; }
        public Nullable<double> TotalDueAmount { get; set; }
        public int EmployeeId { get; set; }
        public string Note { get; set; }
        public int PaymentStatusId { get; set; }
        public Nullable<System.DateTime> PaymentCompleteDate { get; set; }
        public Nullable<bool> IsInvoiceCompleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DemandOrderType DemandOrderType { get; set; }
        public virtual DiscountType DiscountType { get; set; }
        public virtual RejectedReasonType RejectedReasonType { get; set; }
        public virtual SaleType SaleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandOrderDetail> DemandOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandOrderDiscountTransaction> DemandOrderDiscountTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandOrderTransaction> DemandOrderTransaction { get; set; }
        public virtual DemandOrderStatus DemandOrderStatus { get; set; }
        public virtual DemandOrderTransaction DemandOrderTransaction1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
