//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeHistory()
        {
            this.EmployeeSalesLocationHistory = new HashSet<EmployeeSalesLocationHistory>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string BloodGroup { get; set; }
        public string ImageId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SalesDivisionId { get; set; }
        public Nullable<int> SalesAreaId { get; set; }
        public Nullable<int> SalesBaseId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalesLocationHistory> EmployeeSalesLocationHistory { get; set; }
        public virtual SalesArea SalesArea { get; set; }
        public virtual SalesBase SalesBase { get; set; }
        public virtual SalesDivision SalesDivision { get; set; }
    }
}
