//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Customer = new HashSet<Customer>();
            this.DemandOrder = new HashSet<DemandOrder>();
            this.Employee1 = new HashSet<Employee>();
            this.EmployeeHistory = new HashSet<EmployeeHistory>();
            this.EmployeeSalesLocation = new HashSet<EmployeeSalesLocation>();
            this.EmployeeSalesLocationHistory = new HashSet<EmployeeSalesLocationHistory>();
            this.EmployeeLeave = new HashSet<EmployeeLeave>();
            this.EmployeeSalesTargetMonthly = new HashSet<EmployeeSalesTargetMonthly>();
        }
    
        public int Id { get; set; }
        public int EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostOfficeId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public string BloodGroup { get; set; }
        public string ImageId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SalesDivisionId { get; set; }
        public Nullable<int> SalesAreaId { get; set; }
        public Nullable<int> SalesBaseId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public Nullable<System.DateTime> JobConfirmationDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandOrder> DemandOrder { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHistory> EmployeeHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalesLocation> EmployeeSalesLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalesLocationHistory> EmployeeSalesLocationHistory { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual SalesArea SalesArea { get; set; }
        public virtual SalesBase SalesBase { get; set; }
        public virtual SalesDivision SalesDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeave> EmployeeLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalesTargetMonthly> EmployeeSalesTargetMonthly { get; set; }
    }
}
