//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int LeaveCategoryId { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<int> UnpaidLeaveDays { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ReasonOfLeave { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateOfApplication { get; set; }
        public Nullable<bool> ApprovedByDepartmentHead { get; set; }
        public Nullable<bool> ApprovedByMD { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int LeaveYear { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedByAdminOn { get; set; }
        public Nullable<System.DateTime> ApprovedByHeadOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveCategory LeaveCategory { get; set; }
    }
}
