//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalesLocation
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int DivisionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> BaseId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalesArea SalesArea { get; set; }
        public virtual SalesBase SalesBase { get; set; }
        public virtual SalesDivision SalesDivision { get; set; }
    }
}
