//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedGood
    {
        public int Id { get; set; }
        public int ProductionGroupId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductionGroup ProductionGroup { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
