//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyProcessing
    {
        public int Id { get; set; }
        public int ProcessingTypeId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ReprocessedBy { get; set; }
        public Nullable<System.DateTime> ReprocessedOn { get; set; }
    
        public virtual ProcessingType ProcessingType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
