//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSetting
    {
        public int Id { get; set; }
        public int DocumentRenewalCategoryId { get; set; }
        public int FirstNotificationDays { get; set; }
        public int SecondNotificationDays { get; set; }
        public int FinalNotificationDays { get; set; }
        public bool FirstNotificationContinuity { get; set; }
        public bool SecondNotificationContinuity { get; set; }
    
        public virtual DocumentRenewalCategory DocumentRenewalCategory { get; set; }
    }
}
