//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPSDbContext : DbContext
    {
        public PPSDbContext()   
            : base("name=PPSDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountHead> AccountHead { get; set; }
        public virtual DbSet<AccountHeadOpening> AccountHeadOpening { get; set; }
        public virtual DbSet<AccountNature> AccountNature { get; set; }
        public virtual DbSet<AccountPrimaryHead> AccountPrimaryHead { get; set; }
        public virtual DbSet<AccountSubHead> AccountSubHead { get; set; }
        public virtual DbSet<AccountType> AccountType { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AttachmentType> AttachmentType { get; set; }
        public virtual DbSet<BankInfo> BankInfo { get; set; }
        public virtual DbSet<BatchProduct> BatchProduct { get; set; }
        public virtual DbSet<BatchRequisition> BatchRequisition { get; set; }
        public virtual DbSet<BatchRequisitionDetail> BatchRequisitionDetail { get; set; }
        public virtual DbSet<BatchRequisitionProductionEstimation> BatchRequisitionProductionEstimation { get; set; }
        public virtual DbSet<ClientInfo> ClientInfo { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyHolidays> CompanyHolidays { get; set; }
        public virtual DbSet<CompanyLeave> CompanyLeave { get; set; }
        public virtual DbSet<CompanySalesTarget> CompanySalesTarget { get; set; }
        public virtual DbSet<ControlType> ControlType { get; set; }
        public virtual DbSet<CrashedGood> CrashedGood { get; set; }
        public virtual DbSet<CurrentProductStock> CurrentProductStock { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAttachment> CustomerAttachment { get; set; }
        public virtual DbSet<CustomerHistory> CustomerHistory { get; set; }
        public virtual DbSet<CustomerSalesCredit> CustomerSalesCredit { get; set; }
        public virtual DbSet<CustomerSalesCreditHistory> CustomerSalesCreditHistory { get; set; }
        public virtual DbSet<CustomerStatus> CustomerStatus { get; set; }
        public virtual DbSet<CustomerTransaction> CustomerTransaction { get; set; }
        public virtual DbSet<CustomerTransactionDetail> CustomerTransactionDetail { get; set; }
        public virtual DbSet<CustomerTransactionMonthly> CustomerTransactionMonthly { get; set; }
        public virtual DbSet<CustomerType> CustomerType { get; set; }
        public virtual DbSet<DeliveryQuantity> DeliveryQuantity { get; set; }
        public virtual DbSet<DeliveryQuantityDetail> DeliveryQuantityDetail { get; set; }
        public virtual DbSet<DemandOrder> DemandOrder { get; set; }
        public virtual DbSet<DemandOrderDetail> DemandOrderDetail { get; set; }
        public virtual DbSet<DemandOrderDiscountTransaction> DemandOrderDiscountTransaction { get; set; }
        public virtual DbSet<DemandOrderDiscountType> DemandOrderDiscountType { get; set; }
        public virtual DbSet<DemandOrderStatus> DemandOrderStatus { get; set; }
        public virtual DbSet<DemandOrderTransaction> DemandOrderTransaction { get; set; }
        public virtual DbSet<DemandOrderType> DemandOrderType { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Designation> Designation { get; set; }
        public virtual DbSet<DiscountType> DiscountType { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<DocumentRenewalCategory> DocumentRenewalCategory { get; set; }
        public virtual DbSet<DocumentStatus> DocumentStatus { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeHistory> EmployeeHistory { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeave { get; set; }
        public virtual DbSet<EmployeeSalesLocation> EmployeeSalesLocation { get; set; }
        public virtual DbSet<EmployeeSalesLocationHistory> EmployeeSalesLocationHistory { get; set; }
        public virtual DbSet<EmployeeSalesTargetMonthly> EmployeeSalesTargetMonthly { get; set; }
        public virtual DbSet<EmployeeType> EmployeeType { get; set; }
        public virtual DbSet<EntityType> EntityType { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<FinishedGood> FinishedGood { get; set; }
        public virtual DbSet<FinishedGoodOpening> FinishedGoodOpening { get; set; }
        public virtual DbSet<FiscalYear> FiscalYear { get; set; }
        public virtual DbSet<FloorStoreRawMaterial> FloorStoreRawMaterial { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual DbSet<InvoiceReturn> InvoiceReturn { get; set; }
        public virtual DbSet<InvoiceReturnDetail> InvoiceReturnDetail { get; set; }
        public virtual DbSet<InvoiceTransaction> InvoiceTransaction { get; set; }
        public virtual DbSet<LeaveCategory> LeaveCategory { get; set; }
        public virtual DbSet<LegalDocument> LegalDocument { get; set; }
        public virtual DbSet<LegalDocumentHistory> LegalDocumentHistory { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<MasterSetting> MasterSetting { get; set; }
        public virtual DbSet<MonthlyProcessing> MonthlyProcessing { get; set; }
        public virtual DbSet<NotificationSetting> NotificationSetting { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<PoliceStation> PoliceStation { get; set; }
        public virtual DbSet<Policy> Policy { get; set; }
        public virtual DbSet<PostOffice> PostOffice { get; set; }
        public virtual DbSet<ProcessingType> ProcessingType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductDamageStatusType> ProductDamageStatusType { get; set; }
        public virtual DbSet<ProductHistory> ProductHistory { get; set; }
        public virtual DbSet<ProductionForecastMonthly> ProductionForecastMonthly { get; set; }
        public virtual DbSet<ProductionGroup> ProductionGroup { get; set; }
        public virtual DbSet<ProductStandardType> ProductStandardType { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<ProductTypeGroup> ProductTypeGroup { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public virtual DbSet<PurchaseOrderStatus> PurchaseOrderStatus { get; set; }
        public virtual DbSet<PurchaseOrderTransaction> PurchaseOrderTransaction { get; set; }
        public virtual DbSet<RawMaterialType> RawMaterialType { get; set; }
        public virtual DbSet<ReferenceColumn> ReferenceColumn { get; set; }
        public virtual DbSet<ReferenceTable> ReferenceTable { get; set; }
        public virtual DbSet<RejectedReasonType> RejectedReasonType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RolePolicy> RolePolicy { get; set; }
        public virtual DbSet<RolePolicyHistory> RolePolicyHistory { get; set; }
        public virtual DbSet<RouteResource> RouteResource { get; set; }
        public virtual DbSet<SalesArea> SalesArea { get; set; }
        public virtual DbSet<SalesBase> SalesBase { get; set; }
        public virtual DbSet<SalesDivision> SalesDivision { get; set; }
        public virtual DbSet<SaleType> SaleType { get; set; }
        public virtual DbSet<StoreRawMaterial> StoreRawMaterial { get; set; }
        public virtual DbSet<StoreRawMaterialOpening> StoreRawMaterialOpening { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SystemWarning> SystemWarning { get; set; }
        public virtual DbSet<SystemWarningHistory> SystemWarningHistory { get; set; }
        public virtual DbSet<SystemWarningType> SystemWarningType { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetail { get; set; }
        public virtual DbSet<TransactionDetailHistory> TransactionDetailHistory { get; set; }
        public virtual DbSet<TransactionEntry> TransactionEntry { get; set; }
        public virtual DbSet<TransactionEntryHistory> TransactionEntryHistory { get; set; }
        public virtual DbSet<TransactionRejectReasonType> TransactionRejectReasonType { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatus { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserActivityLog> UserActivityLog { get; set; }
        public virtual DbSet<UserLoginLog> UserLoginLog { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRoleHistory> UserRoleHistory { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
    }
}
