//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHistory
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public Nullable<int> ProductStandardTypeId { get; set; }
        public string Thickness { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public decimal UnitPrice { get; set; }
        public int ProductTypeId { get; set; }
        public int AccountHeadId { get; set; }
        public int HistoryById { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public Nullable<int> BatchId { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductStandardType ProductStandardType { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
