//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BatchProduct = new HashSet<BatchProduct>();
            this.BatchRequisitionProductionEstimation = new HashSet<BatchRequisitionProductionEstimation>();
            this.CurrentProductStock = new HashSet<CurrentProductStock>();
            this.DeliveryQuantityDetail = new HashSet<DeliveryQuantityDetail>();
            this.DemandOrderDetail = new HashSet<DemandOrderDetail>();
            this.FinishedGood = new HashSet<FinishedGood>();
            this.FinishedGoodOpening = new HashSet<FinishedGoodOpening>();
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
            this.InvoiceReturnDetail = new HashSet<InvoiceReturnDetail>();
            this.ProductHistory = new HashSet<ProductHistory>();
            this.ProductionForecastMonthly = new HashSet<ProductionForecastMonthly>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Color { get; set; }
        public Nullable<int> ProductStandardTypeId { get; set; }
        public string Thickness { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public decimal UnitPrice { get; set; }
        public int ProductTypeId { get; set; }
        public int AccountHeadId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProduct> BatchProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRequisitionProductionEstimation> BatchRequisitionProductionEstimation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentProductStock> CurrentProductStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryQuantityDetail> DeliveryQuantityDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandOrderDetail> DemandOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGoodOpening> FinishedGoodOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReturnDetail> InvoiceReturnDetail { get; set; }
        public virtual ProductStandardType ProductStandardType { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHistory> ProductHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionForecastMonthly> ProductionForecastMonthly { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
