//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PurchaseOrderTransaction = new HashSet<PurchaseOrderTransaction>();
            this.StoreRawMaterial = new HashSet<StoreRawMaterial>();
            this.PurchaseOrderDetail = new HashSet<PurchaseOrderDetail>();
        }
    
        public int Id { get; set; }
        public int PurchaseOrderNo { get; set; }
        public System.DateTime PurchaseOrderDate { get; set; }
        public Nullable<bool> IsCashPurchase { get; set; }
        public Nullable<bool> IsCreditPurchase { get; set; }
        public Nullable<bool> IsLcPurchase { get; set; }
        public string Note { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
        public Nullable<int> PriceValidity { get; set; }
        public double TotalAmount { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpatedBy { get; set; }
        public Nullable<System.DateTime> UpatedOn { get; set; }
        public bool IsCurrentRecord { get; set; }
        public Nullable<int> PreviousId { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> RejectedReasonTypeId { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public Nullable<int> PurchaseOrderStatusId { get; set; }
        public Nullable<int> CashAccountHeadId { get; set; }
        public Nullable<double> CashAmount { get; set; }
        public Nullable<int> BankAccountHeadId { get; set; }
        public Nullable<double> BankAmount { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> SupplierAccountHeadId { get; set; }
        public Nullable<double> SupplierAmount { get; set; }
        public string LCNo { get; set; }
        public Nullable<int> LCAccountHeadId { get; set; }
        public Nullable<double> LCAmount { get; set; }
        public Nullable<int> TransactionEntryId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public bool IsPaymentComplete { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual AccountHead AccountHead1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderTransaction> PurchaseOrderTransaction { get; set; }
        public virtual PurchaseOrderStatus PurchaseOrderStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreRawMaterial> StoreRawMaterial { get; set; }
        public virtual RejectedReasonType RejectedReasonType { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
    }
}
