//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialType()
        {
            this.BatchRequisitionDetail = new HashSet<BatchRequisitionDetail>();
            this.FloorStoreRawMaterial = new HashSet<FloorStoreRawMaterial>();
            this.PurchaseOrderDetail = new HashSet<PurchaseOrderDetail>();
            this.StoreRawMaterial = new HashSet<StoreRawMaterial>();
            this.StoreRawMaterialOpening = new HashSet<StoreRawMaterialOpening>();
        }
    
        public int Id { get; set; }
        public string RawMaterialTypeName { get; set; }
        public int UnitTypeId { get; set; }
        public int AccountHeadId { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchRequisitionDetail> BatchRequisitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorStoreRawMaterial> FloorStoreRawMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreRawMaterial> StoreRawMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreRawMaterialOpening> StoreRawMaterialOpening { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
