//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceColumn
    {
        public int Id { get; set; }
        public Nullable<int> CustomerAccountSubHeadId { get; set; }
        public Nullable<int> BankAccountSubHeadId { get; set; }
        public Nullable<int> CashAccountSubHeadId { get; set; }
        public Nullable<int> SalesAccountHeadId { get; set; }
        public Nullable<int> SupplierAccountSubHeadId { get; set; }
    }
}
