//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePolicyHistory
    {
        public int Id { get; set; }
        public int RolePolicyId { get; set; }
        public int RoleId { get; set; }
        public int PolicyId { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Role Role { get; set; }
    }
}
