//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.PurchaseOrderTransaction = new HashSet<PurchaseOrderTransaction>();
        }
    
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public int SupplierCode { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string ContactPersonPhone { get; set; }
        public string Email { get; set; }
        public string ContactPersonEmail { get; set; }
        public int AccountHeadId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderTransaction> PurchaseOrderTransaction { get; set; }
    }
}
