//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemWarningType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemWarningType()
        {
            this.SystemWarning = new HashSet<SystemWarning>();
            this.SystemWarningHistory = new HashSet<SystemWarningHistory>();
        }
    
        public int Id { get; set; }
        public string SystemWarningTypeName { get; set; }
        public int WarningPeriod { get; set; }
        public int EntityId { get; set; }
        public int EntityTypeId { get; set; }
        public bool Active { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemWarning> SystemWarning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemWarningHistory> SystemWarningHistory { get; set; }
    }
}
