//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemWarningHistory
    {
        public int Id { get; set; }
        public int SystemWarningId { get; set; }
        public int SystemWarningTypeId { get; set; }
        public int EntityId { get; set; }
        public string Message { get; set; }
        public int WarningDays { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual SystemWarning SystemWarning { get; set; }
        public virtual SystemWarningType SystemWarningType { get; set; }
    }
}
