//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionDetail()
        {
            this.CustomerTransaction = new HashSet<CustomerTransaction>();
            this.CustomerTransaction1 = new HashSet<CustomerTransaction>();
            this.CustomerTransactionDetail = new HashSet<CustomerTransactionDetail>();
        }
    
        public int Id { get; set; }
        public int AccountHeadId { get; set; }
        public double DrAmount { get; set; }
        public double CrAmount { get; set; }
        public int TransactionEntryId { get; set; }
        public string Note { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransaction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransactionDetail> CustomerTransactionDetail { get; set; }
        public virtual TransactionEntry TransactionEntry { get; set; }
    }
}
