//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEntryHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionEntryHistory()
        {
            this.TransactionDetailHistory = new HashSet<TransactionDetailHistory>();
        }
    
        public int Id { get; set; }
        public int TransactionEntryId { get; set; }
        public string TransactionNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int FiscalYear { get; set; }
        public int TransactionTypeId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime PostingDate { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public bool Accepted { get; set; }
        public Nullable<int> AcceptedById { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<int> PreviousId { get; set; }
        public string UpdateReason { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Particulars { get; set; }
        public Nullable<int> RejectedById { get; set; }
        public Nullable<int> RejectedReasonTypeId { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<int> VerifiedById { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsSystemGenerated { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetailHistory> TransactionDetailHistory { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
