//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserEmail { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public decimal Elapsed { get; set; }
        public string RequestUri { get; set; }
        public string ReferrerUri { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
