CREATE TABLE [dbo].[Customer] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
	[CustomerName]    VARCHAR (50)  NOT NULL,
    [CustomerCode]            INT           NOT NULL,
    [CustomerAddress] VARCHAR (300) NOT NULL,
    [CustomerMobile]          VARCHAR (16)  NULL,
    [CustomerPhone]           VARCHAR (16)  NULL,
    [OwnerName]    VARCHAR (100)  NOT NULL,
	[OwnerMobile]          VARCHAR (16)  NULL,
    [OwnerPhone]           VARCHAR (16)  NULL,
    [OwnerBirthDate] DATE NULL, 
    [ContactPersonName] VARCHAR(100) NULL, 
    [ContactPersonMobile] VARCHAR(16) NULL, 
    [PrimaryContactNo] VARCHAR(16) NULL, 
    [Village]         VARCHAR (100) NULL,
    [PostOfficeId]    INT           NULL,
    [Email]           VARCHAR (50)  NULL,
    [AreaId]          INT           NULL,
    [EmployeeId]          INT           NULL,
    [CustomerTypeId]  INT           NULL,
    [AccountHeadId]   INT			NULL, 
	[CustomerStatusId] INT NULL,
	[CreatedBy]     INT           NULL,
    [CreatedOn]     DATETIME      NULL,
	[UpdatedBy]     INT           NULL,
    [UpdatedOn]     DATETIME      NULL,
    CONSTRAINT [Customer_Primary_Key] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [Customer_Area_Foreign_Key] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[Area] ([Id]),
    CONSTRAINT [Customer_CustomerType_Foreign_Key] FOREIGN KEY ([CustomerTypeId]) REFERENCES [dbo].[CustomerType] ([Id]),
    CONSTRAINT [Customer_PostOffice_Foreign_Key] FOREIGN KEY ([PostOfficeId]) REFERENCES [dbo].[PostOffice] ([Id]),
    CONSTRAINT [Customer_AccountHead_Foreign_Key] FOREIGN KEY ([AccountHeadId]) REFERENCES [dbo].[AccountHead] ([Id]),
    CONSTRAINT [Customer_CustomerStatus_Foreign_Key] FOREIGN KEY ([CustomerStatusId]) REFERENCES [dbo].[CustomerStatus] ([Id]), 
    CONSTRAINT [FK_Customer_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee]([Id])
);

