CREATE TABLE [dbo].[DemandOrder] (
    [Id]                   INT          IDENTITY (1, 1) NOT NULL,
    [DemandOrderNo]        INT          UNIQUE NOT NULL,
    [CustomerId]           INT          NOT NULL,
    [DemandOrderTypeId]    INT          NOT NULL,
    [DiscountTypeId]       INT          NULL,
    [DODate]               DATETIME     NOT NULL,
    [VerifiedBy]           INT          NULL,
    [VerifiedOn]           DATETIME     NULL,
    [ApprovedBy]           INT          NULL,
    [ApprovedOn]           DATETIME     NULL,
    [ReferenceDONo]        VARCHAR (25) NULL,
    [SubmittedBy]          INT          NULL,
    [SubmittedOn]          DATETIME     NULL,
    [RejectedBy]           INT          NULL,
    [RejectedOn]           DATETIME     NULL,
    [ReturnedBy]           INT          NULL,
    [ReturnedOn]           DATETIME     NULL,
    [CreatedBy]            INT          NOT NULL,
    [CreatedOn]            DATETIME     NOT NULL,
	[UpdatedBy]            INT          NULL,
    [UpdatedOn]            DATETIME     NULL,
	[DeliveryConfirmedBy] INT NULL, 
    [DeliveryConfirmedOn] DATETIME NULL,
    [IsCurrentRecord]      BIT          NOT NULL,
    [PreviousId]           INT          NULL,
    [Locked]               BIT          NOT NULL,
    [RejectedReasonTypeId] INT          NULL,
    [SaleTypeId]           INT          NOT NULL,
    [DemandOrderStatusId] INT NOT NULL , 
    [DemandOrderTransactionId] INT NULL , 
    [TotalAmount] FLOAT NOT NULL, 
	[RegularDiscountInPercentage] FLOAT NULL, 
    [RegularDiscountAmount] FLOAT NULL, 
	[SpecialDiscountInPercentage] FLOAT NULL, 
    [SpecialDiscountAmount] FLOAT NULL, 
	[AdditionalDiscountInPercentage] FLOAT NULL, 
    [AdditionalDiscountAmount] FLOAT NULL, 
	[ExtraDiscountInPercentage] FLOAT NULL, 
    [ExtraDiscountAmount] FLOAT NULL, 
    [CashBackAmount] FLOAT NULL, 
	[TotalDiscountAmount] FLOAT NULL, 
    [TotalGrandAmount] FLOAT NOT NULL, 
    [TotalDueAmount] FLOAT NULL,      
    [EmployeeId] INT NOT NULL, 
	[Note] VARCHAR(250) NULL, 
    [PaymentStatusId] INT NOT NULL DEFAULT 1, 
    [PaymentCompleteDate] DATETIME NULL, 
    [IsInvoiceCompleted] BIT NULL DEFAULT 0, 
    CONSTRAINT [DemandOrder_Primary_Key] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [DemandOrder_DemandOrderType_Foreign_Key] FOREIGN KEY ([DemandOrderTypeId]) REFERENCES [dbo].[DemandOrderType] ([Id]),
    CONSTRAINT [DemandOrder_DiscountType_Foreign_Key] FOREIGN KEY ([DiscountTypeId]) REFERENCES [dbo].[DiscountType] ([Id]),
    CONSTRAINT [DemandOrder_RejectedReasonType_Foreign_Key] FOREIGN KEY ([RejectedReasonTypeId]) REFERENCES [dbo].[RejectedReasonType] ([Id]),
    CONSTRAINT [DemandOrder_SaleType_Foreign_Key] FOREIGN KEY ([SaleTypeId]) REFERENCES [dbo].[SaleType] ([Id]),
    CONSTRAINT [FK_DemandOrder_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([Id]),
    CONSTRAINT [FK_DemandOrder_User] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_DemandOrder_DemandOrderStatus] FOREIGN KEY ([DemandOrderStatusId]) REFERENCES [dbo].[DemandOrderStatus] ([Id]),
    CONSTRAINT [FK_DemandOrder_DemandOrderTransaction] FOREIGN KEY ([DemandOrderTransactionId]) REFERENCES [dbo].[DemandOrderTransaction] ([Id]), 
    CONSTRAINT [FK_DemandOrder_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee]([Id]),
	CONSTRAINT [FK_DemandOrder_PaymentStatus] FOREIGN KEY ([PaymentStatusId]) REFERENCES [PaymentStatus]([Id])
);