CREATE TABLE [dbo].[Employee] (
    [Id]           INT           IDENTITY (1, 1) NOT NULL,
    [EmployeeCode]   INT  NOT NULL,
    [FirstName]    VARCHAR (50)  NOT NULL,
    [LastName]     VARCHAR (50)  NOT NULL,
    [Address] VARCHAR(300) NULL, 
    [PostOfficeId] INT           NULL,
    [Email]        VARCHAR (50)  NOT NULL,
    [Mobile]       VARCHAR (16)  NOT NULL,
    [Phone]        VARCHAR (16)  NULL,
    [DepartmentId] INT           NULL,
	[EmployeeTypeId] INT  NULL,
    [BloodGroup]   VARCHAR (10)  NULL,
    [ImageId]      VARCHAR (300) NULL,
    [DesignationId] INT NULL, 
	[ManagerId] INT NULL,     
    [IsActive] BIT NOT NULL , 
    [SalesDivisionId] INT NULL, 
    [SalesAreaId] INT NULL, 
    [SalesBaseId] INT NULL, 
    [CompanyId] INT NULL , 
    [DateOfJoin] DATE NULL, 
    [JobConfirmationDate] DATE NULL, 
    CONSTRAINT [Employee_Primary_Key] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [Employee_Department_Foreign_Key] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [Employee_PostOffice_Foreign_Key] FOREIGN KEY ([PostOfficeId]) REFERENCES [dbo].[PostOffice] ([Id]),
    CONSTRAINT [Employee_Designation_Foreign_Key] FOREIGN KEY ([DesignationId]) REFERENCES [dbo].[Designation] ([Id]),
    CONSTRAINT [Employee_Manager_Foreign_Key] FOREIGN KEY ([ManagerId]) REFERENCES [dbo].[Employee] ([Id]), 
    CONSTRAINT [Employee_Unique_Key] UNIQUE ([EmployeeCode]), 
    CONSTRAINT [FK_Employee_SalesDivision] FOREIGN KEY ([SalesDivisionId]) REFERENCES [SalesDivision]([Id]),
	CONSTRAINT [FK_Employee_SalesArea] FOREIGN KEY ([SalesAreaId]) REFERENCES [SalesArea]([Id]),
	CONSTRAINT [FK_Employee_SalesBase] FOREIGN KEY ([SalesBaseId]) REFERENCES [SalesBase]([Id]), 
    CONSTRAINT [FK_Employee_Company] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
	CONSTRAINT [FK_Employee_EmployeeType] FOREIGN KEY ([EmployeeTypeId]) REFERENCES [EmployeeType]([Id])
);

